services:
  - type: web
    name: qr-attendance
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn attendance_system.wsgi:application"
    envVars:
      - key: DEBUG
        value: False