# Generated by Django 5.2.6 on 2026-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
