# Generated by Django 5.2.6 on 2026-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
