# Generated by Django 5.2.6 on 2026-05-04 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0007_student_enrollment_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_app.branch'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
